[phases.setup]
nixPkgs = ["nodejs-18_x"]

[phases.install]
cmds = [
  "npm install",
  "cd frontend && npm install"
]

[phases.build]
cmds = ["npm run build"]

[start]
cmd = "NODE_ENV=production node backend/server.js"

